#!/usr/bin/env python

import tomlkit
import requests


def run(config):
    for data_source in config['data_source']:
        url = data_source['url']
        requests.get(url)





if __name__ == "__main__":
    with open('config.toml') as toml_file:
        config = tomlkit.loads(toml_file.read())
        print(config)
