#!/usr/bin/env python
import argparse
import sys

from pypastry.commands.print_ import print_results
from pypastry.commands.run import run

sys.path.append('.')


commands = {
    'run': run,
    'print': print_results,
}


def parse_and_run():
        parser = argparse.ArgumentParser(
            description='Run a machine learning experiment',
            usage='''pastry [<command>] [<args>]

The command can be:
   run        Run an experiment
   print      Print out results from previous experiments
''')
        parser.add_argument('command', help='Subcommand to run')
        args = parser.parse_args(sys.argv[1:2])

        commands[args.command]()


if __name__ == "__main__":
    parse_and_run()
